/**
 * Tebex Checkout API
 * The Checkout APIs are designed to allow our creators to use the Tebex Checkout flow and payment acceptance capabilities without the need to set up a Tebex-powered webstore. Using these APIs allows you to create baskets with custom products (as opposed to pre-created products on our webstore platform), and send customers directly to the checkout flow to proceed with payment options.  You must receive prior authorisation before the Checkout API is enabled on your account. Please contact customer support or your account manager to discover if you qualify to use the Checkout API before beginning integration.
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/TebexCheckout/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/TebexCheckout/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TebexCheckoutApi);
  }
}(this, function(expect, TebexCheckoutApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TebexCheckoutApi.CreateBasketRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateBasketRequest', function() {
    it('should create an instance of CreateBasketRequest', function() {
      // uncomment below and update the code to test CreateBasketRequest
      //var instance = new TebexCheckoutApi.CreateBasketRequest();
      //expect(instance).to.be.a(TebexCheckoutApi.CreateBasketRequest);
    });

    it('should have the property returnUrl (base name: "return_url")', function() {
      // uncomment below and update the code to test the property returnUrl
      //var instance = new TebexCheckoutApi.CreateBasketRequest();
      //expect(instance).to.be();
    });

    it('should have the property completeUrl (base name: "complete_url")', function() {
      // uncomment below and update the code to test the property completeUrl
      //var instance = new TebexCheckoutApi.CreateBasketRequest();
      //expect(instance).to.be();
    });

    it('should have the property custom (base name: "custom")', function() {
      // uncomment below and update the code to test the property custom
      //var instance = new TebexCheckoutApi.CreateBasketRequest();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "first_name")', function() {
      // uncomment below and update the code to test the property firstName
      //var instance = new TebexCheckoutApi.CreateBasketRequest();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "last_name")', function() {
      // uncomment below and update the code to test the property lastName
      //var instance = new TebexCheckoutApi.CreateBasketRequest();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new TebexCheckoutApi.CreateBasketRequest();
      //expect(instance).to.be();
    });

    it('should have the property completeAutoRedirect (base name: "complete_auto_redirect")', function() {
      // uncomment below and update the code to test the property completeAutoRedirect
      //var instance = new TebexCheckoutApi.CreateBasketRequest();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new TebexCheckoutApi.CreateBasketRequest();
      //expect(instance).to.be();
    });

    it('should have the property creatorCode (base name: "creator_code")', function() {
      // uncomment below and update the code to test the property creatorCode
      //var instance = new TebexCheckoutApi.CreateBasketRequest();
      //expect(instance).to.be();
    });

    it('should have the property ip (base name: "ip")', function() {
      // uncomment below and update the code to test the property ip
      //var instance = new TebexCheckoutApi.CreateBasketRequest();
      //expect(instance).to.be();
    });

  });

}));
