/*
 * Tebex Checkout API
 *
 * The Checkout APIs are designed to allow our creators to use the Tebex Checkout flow and payment acceptance capabilities without the need to set up a Tebex-powered webstore. Using these APIs allows you to create baskets with custom products (as opposed to pre-created products on our webstore platform), and send customers directly to the checkout flow to proceed with payment options.  You must receive prior authorisation before the Checkout API is enabled on your account. Please contact customer support or your account manager to discover if you qualify to use the Checkout API before beginning integration.
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: tebex-integrations@overwolf.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = TebexCheckout.Client.OpenAPIDateConverter;

namespace TebexCheckout.Model
{
    /// <summary>
    /// UpdateBasketRequest
    /// </summary>
    [DataContract(Name = "updateBasket_request")]
    public partial class UpdateBasketRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateBasketRequest" /> class.
        /// </summary>
        /// <param name="country">country.</param>
        /// <param name="name">name.</param>
        /// <param name="stateId">stateId.</param>
        /// <param name="firstName">firstName.</param>
        /// <param name="lastName">lastName.</param>
        /// <param name="postalCode">postalCode.</param>
        /// <param name="creatorCode">creatorCode.</param>
        /// <param name="completeAutoRedirect">completeAutoRedirect.</param>
        /// <param name="expiresAt">An ISO8601 formatted date. After this date the basket cannot be used to checkout..</param>
        public UpdateBasketRequest(string country = default(string), string name = default(string), string stateId = default(string), string firstName = default(string), string lastName = default(string), string postalCode = default(string), string creatorCode = default(string), bool? completeAutoRedirect = default(bool?), DateTime? expiresAt = default(DateTime?))
        {
            this.Country = country;
            this.Name = name;
            this.StateId = stateId;
            this.FirstName = firstName;
            this.LastName = lastName;
            this.PostalCode = postalCode;
            this.CreatorCode = creatorCode;
            this.CompleteAutoRedirect = completeAutoRedirect;
            this.ExpiresAt = expiresAt;
        }

        /// <summary>
        /// Gets or Sets Country
        /// </summary>
        [DataMember(Name = "country", EmitDefaultValue = true)]
        public string Country { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets StateId
        /// </summary>
        [DataMember(Name = "state_id", EmitDefaultValue = true)]
        public string StateId { get; set; }

        /// <summary>
        /// Gets or Sets FirstName
        /// </summary>
        [DataMember(Name = "first_name", EmitDefaultValue = true)]
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or Sets LastName
        /// </summary>
        [DataMember(Name = "last_name", EmitDefaultValue = true)]
        public string LastName { get; set; }

        /// <summary>
        /// Gets or Sets PostalCode
        /// </summary>
        [DataMember(Name = "postal_code", EmitDefaultValue = true)]
        public string PostalCode { get; set; }

        /// <summary>
        /// Gets or Sets CreatorCode
        /// </summary>
        [DataMember(Name = "creator_code", EmitDefaultValue = true)]
        public string CreatorCode { get; set; }

        /// <summary>
        /// Gets or Sets CompleteAutoRedirect
        /// </summary>
        [DataMember(Name = "complete_auto_redirect", EmitDefaultValue = true)]
        public bool? CompleteAutoRedirect { get; set; }

        /// <summary>
        /// An ISO8601 formatted date. After this date the basket cannot be used to checkout.
        /// </summary>
        /// <value>An ISO8601 formatted date. After this date the basket cannot be used to checkout.</value>
        /// <example>2025-01-27T18:09:51Z</example>
        [DataMember(Name = "expires_at", EmitDefaultValue = true)]
        public DateTime? ExpiresAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateBasketRequest {\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  StateId: ").Append(StateId).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  PostalCode: ").Append(PostalCode).Append("\n");
            sb.Append("  CreatorCode: ").Append(CreatorCode).Append("\n");
            sb.Append("  CompleteAutoRedirect: ").Append(CompleteAutoRedirect).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
