/**
 * Tebex Checkout API
 * The Checkout APIs are designed to allow our creators to use the Tebex Checkout flow and payment acceptance capabilities without the need to set up a Tebex-powered webstore. Using these APIs allows you to create baskets with custom products (as opposed to pre-created products on our webstore platform), and send customers directly to the checkout flow to proceed with payment options.  You must receive prior authorisation before the Checkout API is enabled on your account. Please contact customer support or your account manager to discover if you qualify to use the Checkout API before beginning integration.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RevenueShare model module.
 * @module TebexCheckout/model/RevenueShare
 * @version 1.1.0
 */
class RevenueShare {
    /**
     * Constructs a new <code>RevenueShare</code>.
     * @alias module:TebexCheckout/model/RevenueShare
     */
    constructor() { 
        
        RevenueShare.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RevenueShare</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:TebexCheckout/model/RevenueShare} obj Optional instance to populate.
     * @return {module:TebexCheckout/model/RevenueShare} The populated <code>RevenueShare</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RevenueShare();

            if (data.hasOwnProperty('wallet_ref')) {
                obj['wallet_ref'] = ApiClient.convertToType(data['wallet_ref'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('gateway_fee_percent')) {
                obj['gateway_fee_percent'] = ApiClient.convertToType(data['gateway_fee_percent'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RevenueShare</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RevenueShare</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['wallet_ref'] && !(typeof data['wallet_ref'] === 'string' || data['wallet_ref'] instanceof String)) {
            throw new Error("Expected the field `wallet_ref` to be a primitive type in the JSON string but got " + data['wallet_ref']);
        }

        return true;
    }


}



/**
 * @member {String} wallet_ref
 */
RevenueShare.prototype['wallet_ref'] = undefined;

/**
 * A float (decimal) value representing the amount of this payment in your account currency that is credited to the `wallet_ref`
 * @member {Number} amount
 */
RevenueShare.prototype['amount'] = undefined;

/**
 * A float (decimal) value representing the percentage of the gateway fee that should be dedicated from this wallet’s revenue share. This optional value can be anywhere between 0 - 100.
 * @member {Number} gateway_fee_percent
 */
RevenueShare.prototype['gateway_fee_percent'] = undefined;






export default RevenueShare;

