# coding: utf-8

"""
    Tebex Checkout API

    The Checkout APIs are designed to allow our creators to use the Tebex Checkout flow and payment acceptance capabilities without the need to set up a Tebex-powered webstore. Using these APIs allows you to create baskets with custom products (as opposed to pre-created products on our webstore platform), and send customers directly to the checkout flow to proceed with payment options.  You must receive prior authorisation before the Checkout API is enabled on your account. Please contact customer support or your account manager to discover if you qualify to use the Checkout API before beginning integration.

    The version of the OpenAPI document: 1.1.4
    Contact: tebex-integrations@overwolf.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from TebexCheckout.models.tebex_webhook import TebexWebhook

class TestTebexWebhook(unittest.TestCase):
    """TebexWebhook unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TebexWebhook:
        """Test TebexWebhook
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TebexWebhook`
        """
        model = TebexWebhook()
        if include_optional:
            return TebexWebhook(
                id = 'fcf9cfc9-3708-4942-88f2-78d7e5cd8e72',
                type = 'validation.webhook',
                var_date = '2024-07-02T19:52:07+00:00',
                subject = None
            )
        else:
            return TebexWebhook(
        )
        """

    def testTebexWebhook(self):
        """Test TebexWebhook"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
