# coding: utf-8

"""
    Tebex Checkout API

    The Checkout APIs are designed to allow our creators to use the Tebex Checkout flow and payment acceptance capabilities without the need to set up a Tebex-powered webstore. Using these APIs allows you to create baskets with custom products (as opposed to pre-created products on our webstore platform), and send customers directly to the checkout flow to proceed with payment options.  You must receive prior authorisation before the Checkout API is enabled on your account. Please contact customer support or your account manager to discover if you qualify to use the Checkout API before beginning integration.

    The version of the OpenAPI document: 1.1.2
    Contact: tebex-integrations@overwolf.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from TebexCheckout.recurring_payments_api import RecurringPaymentsApi


class TestRecurringPaymentsApi(unittest.TestCase):
    """RecurringPaymentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecurringPaymentsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_recurring_payment(self) -> None:
        """Test case for cancel_recurring_payment

        Cancel a recurring payment
        """
        pass

    def test_get_recurring_payment(self) -> None:
        """Test case for get_recurring_payment

        Fetch a recurring payment (subscription) by its reference
        """
        pass

    def test_update_recurring_payment(self) -> None:
        """Test case for update_recurring_payment

        Pause or reactivate a recurring payment
        """
        pass

    def test_update_subscription(self) -> None:
        """Test case for update_subscription

        Update a subscription with a new product / amount to pay - replacing the existing product
        """
        pass


if __name__ == '__main__':
    unittest.main()
