/**
 * Tebex Checkout API
 * The Checkout APIs are designed to allow our creators to use the Tebex Checkout flow and payment acceptance capabilities without the need to set up a Tebex-powered webstore. Using these APIs allows you to create baskets with custom products (as opposed to pre-created products on our webstore platform), and send customers directly to the checkout flow to proceed with payment options.  You must receive prior authorisation before the Checkout API is enabled on your account. Please contact customer support or your account manager to discover if you qualify to use the Checkout API before beginning integration.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Package } from '../models/Package';
import { RevenueShare } from '../models/RevenueShare';
import { HttpFile } from '../http/http';

export class AddPackageRequest {
    '_package'?: Package;
    /**
    * The quantity of `package` in this basket. This is not the total quantity of overall items in the basket.
    */
    'qty'?: number;
    /**
    * The type of payment, either `single` for one-time payments or `subscription`.
    */
    'type'?: AddPackageRequestTypeEnum;
    /**
    * An array of payment destination objects describing how the purchase should be split between multiple wallets. **Only available with pre-agreement from Tebex.**
    */
    'revenueShare'?: Array<RevenueShare>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "_package",
            "baseName": "package",
            "type": "Package",
            "format": ""
        },
        {
            "name": "qty",
            "baseName": "qty",
            "type": "number",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "AddPackageRequestTypeEnum",
            "format": ""
        },
        {
            "name": "revenueShare",
            "baseName": "revenue_share",
            "type": "Array<RevenueShare>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AddPackageRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AddPackageRequestTypeEnum {
    Single = 'single',
    Subscription = 'subscription'
}

