/**
 * Tebex Checkout API
 * The Checkout APIs are designed to allow our creators to use the Tebex Checkout flow and payment acceptance capabilities without the need to set up a Tebex-powered webstore. Using these APIs allows you to create baskets with custom products (as opposed to pre-created products on our webstore platform), and send customers directly to the checkout flow to proceed with payment options.  You must receive prior authorisation before the Checkout API is enabled on your account. Please contact customer support or your account manager to discover if you qualify to use the Checkout API before beginning integration.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: tebex-integrations@overwolf.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BasketLinks {
    /**
    * The `links.payment` property is only returned if the basket has been paid for and a payment exists with the `complete`,`refund`, or `chargeback` status.
    */
    'payment'?: string;
    /**
    * The `links.checkout` property is only returned if the basket has not been paid, and is the URL to send the customer to make payment
    */
    'checkout'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "payment",
            "baseName": "payment",
            "type": "string",
            "format": ""
        },
        {
            "name": "checkout",
            "baseName": "checkout",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BasketLinks.attributeTypeMap;
    }

    public constructor() {
    }
}

