/*
Tebex Checkout API

The Checkout APIs are designed to allow our creators to use the Tebex Checkout flow and payment acceptance capabilities without the need to set up a Tebex-powered webstore. Using these APIs allows you to create baskets with custom products (as opposed to pre-created products on our webstore platform), and send customers directly to the checkout flow to proceed with payment options.  You must receive prior authorisation before the Checkout API is enabled on your account. Please contact customer support or your account manager to discover if you qualify to use the Checkout API before beginning integration.

API version: 1.0.0
Contact: tebex-integrations@overwolf.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package TebexCheckout

import (
	"encoding/json"
)

// checks if the PaymentProductsInnerBasePrice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentProductsInnerBasePrice{}

// PaymentProductsInnerBasePrice struct for PaymentProductsInnerBasePrice
type PaymentProductsInnerBasePrice struct {
	Amount *float32 `json:"amount,omitempty"`
	Currency *string `json:"currency,omitempty"`
}

// NewPaymentProductsInnerBasePrice instantiates a new PaymentProductsInnerBasePrice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentProductsInnerBasePrice() *PaymentProductsInnerBasePrice {
	this := PaymentProductsInnerBasePrice{}
	return &this
}

// NewPaymentProductsInnerBasePriceWithDefaults instantiates a new PaymentProductsInnerBasePrice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentProductsInnerBasePriceWithDefaults() *PaymentProductsInnerBasePrice {
	this := PaymentProductsInnerBasePrice{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *PaymentProductsInnerBasePrice) GetAmount() float32 {
	if o == nil || IsNil(o.Amount) {
		var ret float32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentProductsInnerBasePrice) GetAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *PaymentProductsInnerBasePrice) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float32 and assigns it to the Amount field.
func (o *PaymentProductsInnerBasePrice) SetAmount(v float32) {
	o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *PaymentProductsInnerBasePrice) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentProductsInnerBasePrice) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *PaymentProductsInnerBasePrice) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *PaymentProductsInnerBasePrice) SetCurrency(v string) {
	o.Currency = &v
}

func (o PaymentProductsInnerBasePrice) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentProductsInnerBasePrice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	return toSerialize, nil
}

type NullablePaymentProductsInnerBasePrice struct {
	value *PaymentProductsInnerBasePrice
	isSet bool
}

func (v NullablePaymentProductsInnerBasePrice) Get() *PaymentProductsInnerBasePrice {
	return v.value
}

func (v *NullablePaymentProductsInnerBasePrice) Set(val *PaymentProductsInnerBasePrice) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentProductsInnerBasePrice) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentProductsInnerBasePrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentProductsInnerBasePrice(val *PaymentProductsInnerBasePrice) *NullablePaymentProductsInnerBasePrice {
	return &NullablePaymentProductsInnerBasePrice{value: val, isSet: true}
}

func (v NullablePaymentProductsInnerBasePrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentProductsInnerBasePrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


