/*
Tebex Checkout API

The Checkout APIs are designed to allow our creators to use the Tebex Checkout flow and payment acceptance capabilities without the need to set up a Tebex-powered webstore. Using these APIs allows you to create baskets with custom products (as opposed to pre-created products on our webstore platform), and send customers directly to the checkout flow to proceed with payment options.  You must receive prior authorisation before the Checkout API is enabled on your account. Please contact customer support or your account manager to discover if you qualify to use the Checkout API before beginning integration.

API version: 1.0.0
Contact: tebex-integrations@overwolf.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package TebexCheckout

import (
	"encoding/json"
)

// checks if the AddPackageRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddPackageRequest{}

// AddPackageRequest struct for AddPackageRequest
type AddPackageRequest struct {
	Package *Package `json:"package,omitempty"`
	// The quantity of `package` in this basket. This is not the total quantity of overall items in the basket.
	Qty *int32 `json:"qty,omitempty"`
	// The type of payment, either `single` for one-time payments or `subscription`.
	Type *string `json:"type,omitempty"`
	// An array of payment destination objects describing how the purchase should be split between multiple wallets. **Only available with pre-agreement from Tebex.**
	RevenueShare []RevenueShare `json:"revenue_share,omitempty"`
}

// NewAddPackageRequest instantiates a new AddPackageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddPackageRequest() *AddPackageRequest {
	this := AddPackageRequest{}
	return &this
}

// NewAddPackageRequestWithDefaults instantiates a new AddPackageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddPackageRequestWithDefaults() *AddPackageRequest {
	this := AddPackageRequest{}
	return &this
}

// GetPackage returns the Package field value if set, zero value otherwise.
func (o *AddPackageRequest) GetPackage() Package {
	if o == nil || IsNil(o.Package) {
		var ret Package
		return ret
	}
	return *o.Package
}

// GetPackageOk returns a tuple with the Package field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddPackageRequest) GetPackageOk() (*Package, bool) {
	if o == nil || IsNil(o.Package) {
		return nil, false
	}
	return o.Package, true
}

// HasPackage returns a boolean if a field has been set.
func (o *AddPackageRequest) HasPackage() bool {
	if o != nil && !IsNil(o.Package) {
		return true
	}

	return false
}

// SetPackage gets a reference to the given Package and assigns it to the Package field.
func (o *AddPackageRequest) SetPackage(v Package) {
	o.Package = &v
}

// GetQty returns the Qty field value if set, zero value otherwise.
func (o *AddPackageRequest) GetQty() int32 {
	if o == nil || IsNil(o.Qty) {
		var ret int32
		return ret
	}
	return *o.Qty
}

// GetQtyOk returns a tuple with the Qty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddPackageRequest) GetQtyOk() (*int32, bool) {
	if o == nil || IsNil(o.Qty) {
		return nil, false
	}
	return o.Qty, true
}

// HasQty returns a boolean if a field has been set.
func (o *AddPackageRequest) HasQty() bool {
	if o != nil && !IsNil(o.Qty) {
		return true
	}

	return false
}

// SetQty gets a reference to the given int32 and assigns it to the Qty field.
func (o *AddPackageRequest) SetQty(v int32) {
	o.Qty = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *AddPackageRequest) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddPackageRequest) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *AddPackageRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *AddPackageRequest) SetType(v string) {
	o.Type = &v
}

// GetRevenueShare returns the RevenueShare field value if set, zero value otherwise.
func (o *AddPackageRequest) GetRevenueShare() []RevenueShare {
	if o == nil || IsNil(o.RevenueShare) {
		var ret []RevenueShare
		return ret
	}
	return o.RevenueShare
}

// GetRevenueShareOk returns a tuple with the RevenueShare field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddPackageRequest) GetRevenueShareOk() ([]RevenueShare, bool) {
	if o == nil || IsNil(o.RevenueShare) {
		return nil, false
	}
	return o.RevenueShare, true
}

// HasRevenueShare returns a boolean if a field has been set.
func (o *AddPackageRequest) HasRevenueShare() bool {
	if o != nil && !IsNil(o.RevenueShare) {
		return true
	}

	return false
}

// SetRevenueShare gets a reference to the given []RevenueShare and assigns it to the RevenueShare field.
func (o *AddPackageRequest) SetRevenueShare(v []RevenueShare) {
	o.RevenueShare = v
}

func (o AddPackageRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddPackageRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Package) {
		toSerialize["package"] = o.Package
	}
	if !IsNil(o.Qty) {
		toSerialize["qty"] = o.Qty
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.RevenueShare) {
		toSerialize["revenue_share"] = o.RevenueShare
	}
	return toSerialize, nil
}

type NullableAddPackageRequest struct {
	value *AddPackageRequest
	isSet bool
}

func (v NullableAddPackageRequest) Get() *AddPackageRequest {
	return v.value
}

func (v *NullableAddPackageRequest) Set(val *AddPackageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddPackageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddPackageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddPackageRequest(val *AddPackageRequest) *NullableAddPackageRequest {
	return &NullableAddPackageRequest{value: val, isSet: true}
}

func (v NullableAddPackageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddPackageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


