/*
Tebex Checkout API

The Checkout APIs are designed to allow our creators to use the Tebex Checkout flow and payment acceptance capabilities without the need to set up a Tebex-powered webstore. Using these APIs allows you to create baskets with custom products (as opposed to pre-created products on our webstore platform), and send customers directly to the checkout flow to proceed with payment options.  You must receive prior authorisation before the Checkout API is enabled on your account. Please contact customer support or your account manager to discover if you qualify to use the Checkout API before beginning integration.

API version: 1.0.0
Contact: tebex-integrations@overwolf.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package TebexCheckout

import (
	"encoding/json"
)

// checks if the RecurringPaymentLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecurringPaymentLinks{}

// RecurringPaymentLinks struct for RecurringPaymentLinks
type RecurringPaymentLinks struct {
	InitialPayment *string `json:"initial_payment,omitempty"`
	PaymentHistory []string `json:"payment_history,omitempty"`
}

// NewRecurringPaymentLinks instantiates a new RecurringPaymentLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecurringPaymentLinks() *RecurringPaymentLinks {
	this := RecurringPaymentLinks{}
	return &this
}

// NewRecurringPaymentLinksWithDefaults instantiates a new RecurringPaymentLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecurringPaymentLinksWithDefaults() *RecurringPaymentLinks {
	this := RecurringPaymentLinks{}
	return &this
}

// GetInitialPayment returns the InitialPayment field value if set, zero value otherwise.
func (o *RecurringPaymentLinks) GetInitialPayment() string {
	if o == nil || IsNil(o.InitialPayment) {
		var ret string
		return ret
	}
	return *o.InitialPayment
}

// GetInitialPaymentOk returns a tuple with the InitialPayment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecurringPaymentLinks) GetInitialPaymentOk() (*string, bool) {
	if o == nil || IsNil(o.InitialPayment) {
		return nil, false
	}
	return o.InitialPayment, true
}

// HasInitialPayment returns a boolean if a field has been set.
func (o *RecurringPaymentLinks) HasInitialPayment() bool {
	if o != nil && !IsNil(o.InitialPayment) {
		return true
	}

	return false
}

// SetInitialPayment gets a reference to the given string and assigns it to the InitialPayment field.
func (o *RecurringPaymentLinks) SetInitialPayment(v string) {
	o.InitialPayment = &v
}

// GetPaymentHistory returns the PaymentHistory field value if set, zero value otherwise.
func (o *RecurringPaymentLinks) GetPaymentHistory() []string {
	if o == nil || IsNil(o.PaymentHistory) {
		var ret []string
		return ret
	}
	return o.PaymentHistory
}

// GetPaymentHistoryOk returns a tuple with the PaymentHistory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecurringPaymentLinks) GetPaymentHistoryOk() ([]string, bool) {
	if o == nil || IsNil(o.PaymentHistory) {
		return nil, false
	}
	return o.PaymentHistory, true
}

// HasPaymentHistory returns a boolean if a field has been set.
func (o *RecurringPaymentLinks) HasPaymentHistory() bool {
	if o != nil && !IsNil(o.PaymentHistory) {
		return true
	}

	return false
}

// SetPaymentHistory gets a reference to the given []string and assigns it to the PaymentHistory field.
func (o *RecurringPaymentLinks) SetPaymentHistory(v []string) {
	o.PaymentHistory = v
}

func (o RecurringPaymentLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecurringPaymentLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InitialPayment) {
		toSerialize["initial_payment"] = o.InitialPayment
	}
	if !IsNil(o.PaymentHistory) {
		toSerialize["payment_history"] = o.PaymentHistory
	}
	return toSerialize, nil
}

type NullableRecurringPaymentLinks struct {
	value *RecurringPaymentLinks
	isSet bool
}

func (v NullableRecurringPaymentLinks) Get() *RecurringPaymentLinks {
	return v.value
}

func (v *NullableRecurringPaymentLinks) Set(val *RecurringPaymentLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableRecurringPaymentLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableRecurringPaymentLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecurringPaymentLinks(val *RecurringPaymentLinks) *NullableRecurringPaymentLinks {
	return &NullableRecurringPaymentLinks{value: val, isSet: true}
}

func (v NullableRecurringPaymentLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecurringPaymentLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


