/*
Tebex Checkout API

The Checkout APIs are designed to allow our creators to use the Tebex Checkout flow and payment acceptance capabilities without the need to set up a Tebex-powered webstore. Using these APIs allows you to create baskets with custom products (as opposed to pre-created products on our webstore platform), and send customers directly to the checkout flow to proceed with payment options.  You must receive prior authorisation before the Checkout API is enabled on your account. Please contact customer support or your account manager to discover if you qualify to use the Checkout API before beginning integration.

API version: 1.0.0
Contact: tebex-integrations@overwolf.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package TebexCheckout

import (
	"encoding/json"
)

// checks if the CreateBasketRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBasketRequest{}

// CreateBasketRequest struct for CreateBasketRequest
type CreateBasketRequest struct {
	// The URL a customer can return to without completing checkout
	ReturnUrl *string `json:"return_url,omitempty"`
	// URL the customer can return to after completing payment
	CompleteUrl *string `json:"complete_url,omitempty"`
	// Any custom data to be passed through the request. This will be returned in a post-completion webhook.
	Custom map[string]interface{} `json:"custom,omitempty"`
	// The first name of the customer
	FirstName *string `json:"first_name,omitempty"`
	// The last name of the customer
	LastName *string `json:"last_name,omitempty"`
	// The email address of the customer
	Email *string `json:"email,omitempty"`
	// An ISO8601 formatted date. After this date the basket cannot be used to checkout.
	ExpiresAt *string `json:"expires_at,omitempty"`
	// Automatically redirect to the complete_url provided
	CompleteAutoRedirect *bool `json:"complete_auto_redirect,omitempty"`
	// An ISO 3166-1 alpha-2 character code representing the customer's country.
	Country *string `json:"country,omitempty"`
	// The creator code is used to share a percentage of the payment with another party. See more about creator codes at https://docs.tebex.io/creators/tebex-control-panel/engagement/creator-codes
	CreatorCode *string `json:"creator_code,omitempty"`
}

// NewCreateBasketRequest instantiates a new CreateBasketRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBasketRequest() *CreateBasketRequest {
	this := CreateBasketRequest{}
	return &this
}

// NewCreateBasketRequestWithDefaults instantiates a new CreateBasketRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBasketRequestWithDefaults() *CreateBasketRequest {
	this := CreateBasketRequest{}
	return &this
}

// GetReturnUrl returns the ReturnUrl field value if set, zero value otherwise.
func (o *CreateBasketRequest) GetReturnUrl() string {
	if o == nil || IsNil(o.ReturnUrl) {
		var ret string
		return ret
	}
	return *o.ReturnUrl
}

// GetReturnUrlOk returns a tuple with the ReturnUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBasketRequest) GetReturnUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ReturnUrl) {
		return nil, false
	}
	return o.ReturnUrl, true
}

// HasReturnUrl returns a boolean if a field has been set.
func (o *CreateBasketRequest) HasReturnUrl() bool {
	if o != nil && !IsNil(o.ReturnUrl) {
		return true
	}

	return false
}

// SetReturnUrl gets a reference to the given string and assigns it to the ReturnUrl field.
func (o *CreateBasketRequest) SetReturnUrl(v string) {
	o.ReturnUrl = &v
}

// GetCompleteUrl returns the CompleteUrl field value if set, zero value otherwise.
func (o *CreateBasketRequest) GetCompleteUrl() string {
	if o == nil || IsNil(o.CompleteUrl) {
		var ret string
		return ret
	}
	return *o.CompleteUrl
}

// GetCompleteUrlOk returns a tuple with the CompleteUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBasketRequest) GetCompleteUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CompleteUrl) {
		return nil, false
	}
	return o.CompleteUrl, true
}

// HasCompleteUrl returns a boolean if a field has been set.
func (o *CreateBasketRequest) HasCompleteUrl() bool {
	if o != nil && !IsNil(o.CompleteUrl) {
		return true
	}

	return false
}

// SetCompleteUrl gets a reference to the given string and assigns it to the CompleteUrl field.
func (o *CreateBasketRequest) SetCompleteUrl(v string) {
	o.CompleteUrl = &v
}

// GetCustom returns the Custom field value if set, zero value otherwise.
func (o *CreateBasketRequest) GetCustom() map[string]interface{} {
	if o == nil || IsNil(o.Custom) {
		var ret map[string]interface{}
		return ret
	}
	return o.Custom
}

// GetCustomOk returns a tuple with the Custom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBasketRequest) GetCustomOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Custom) {
		return map[string]interface{}{}, false
	}
	return o.Custom, true
}

// HasCustom returns a boolean if a field has been set.
func (o *CreateBasketRequest) HasCustom() bool {
	if o != nil && !IsNil(o.Custom) {
		return true
	}

	return false
}

// SetCustom gets a reference to the given map[string]interface{} and assigns it to the Custom field.
func (o *CreateBasketRequest) SetCustom(v map[string]interface{}) {
	o.Custom = v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *CreateBasketRequest) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBasketRequest) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *CreateBasketRequest) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *CreateBasketRequest) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *CreateBasketRequest) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBasketRequest) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *CreateBasketRequest) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *CreateBasketRequest) SetLastName(v string) {
	o.LastName = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *CreateBasketRequest) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBasketRequest) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *CreateBasketRequest) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *CreateBasketRequest) SetEmail(v string) {
	o.Email = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *CreateBasketRequest) GetExpiresAt() string {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret string
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBasketRequest) GetExpiresAtOk() (*string, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *CreateBasketRequest) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given string and assigns it to the ExpiresAt field.
func (o *CreateBasketRequest) SetExpiresAt(v string) {
	o.ExpiresAt = &v
}

// GetCompleteAutoRedirect returns the CompleteAutoRedirect field value if set, zero value otherwise.
func (o *CreateBasketRequest) GetCompleteAutoRedirect() bool {
	if o == nil || IsNil(o.CompleteAutoRedirect) {
		var ret bool
		return ret
	}
	return *o.CompleteAutoRedirect
}

// GetCompleteAutoRedirectOk returns a tuple with the CompleteAutoRedirect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBasketRequest) GetCompleteAutoRedirectOk() (*bool, bool) {
	if o == nil || IsNil(o.CompleteAutoRedirect) {
		return nil, false
	}
	return o.CompleteAutoRedirect, true
}

// HasCompleteAutoRedirect returns a boolean if a field has been set.
func (o *CreateBasketRequest) HasCompleteAutoRedirect() bool {
	if o != nil && !IsNil(o.CompleteAutoRedirect) {
		return true
	}

	return false
}

// SetCompleteAutoRedirect gets a reference to the given bool and assigns it to the CompleteAutoRedirect field.
func (o *CreateBasketRequest) SetCompleteAutoRedirect(v bool) {
	o.CompleteAutoRedirect = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *CreateBasketRequest) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBasketRequest) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *CreateBasketRequest) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *CreateBasketRequest) SetCountry(v string) {
	o.Country = &v
}

// GetCreatorCode returns the CreatorCode field value if set, zero value otherwise.
func (o *CreateBasketRequest) GetCreatorCode() string {
	if o == nil || IsNil(o.CreatorCode) {
		var ret string
		return ret
	}
	return *o.CreatorCode
}

// GetCreatorCodeOk returns a tuple with the CreatorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateBasketRequest) GetCreatorCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CreatorCode) {
		return nil, false
	}
	return o.CreatorCode, true
}

// HasCreatorCode returns a boolean if a field has been set.
func (o *CreateBasketRequest) HasCreatorCode() bool {
	if o != nil && !IsNil(o.CreatorCode) {
		return true
	}

	return false
}

// SetCreatorCode gets a reference to the given string and assigns it to the CreatorCode field.
func (o *CreateBasketRequest) SetCreatorCode(v string) {
	o.CreatorCode = &v
}

func (o CreateBasketRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBasketRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ReturnUrl) {
		toSerialize["return_url"] = o.ReturnUrl
	}
	if !IsNil(o.CompleteUrl) {
		toSerialize["complete_url"] = o.CompleteUrl
	}
	if !IsNil(o.Custom) {
		toSerialize["custom"] = o.Custom
	}
	if !IsNil(o.FirstName) {
		toSerialize["first_name"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["last_name"] = o.LastName
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	if !IsNil(o.CompleteAutoRedirect) {
		toSerialize["complete_auto_redirect"] = o.CompleteAutoRedirect
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.CreatorCode) {
		toSerialize["creator_code"] = o.CreatorCode
	}
	return toSerialize, nil
}

type NullableCreateBasketRequest struct {
	value *CreateBasketRequest
	isSet bool
}

func (v NullableCreateBasketRequest) Get() *CreateBasketRequest {
	return v.value
}

func (v *NullableCreateBasketRequest) Set(val *CreateBasketRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBasketRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBasketRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBasketRequest(val *CreateBasketRequest) *NullableCreateBasketRequest {
	return &NullableCreateBasketRequest{value: val, isSet: true}
}

func (v NullableCreateBasketRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBasketRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


