/*
Tebex Checkout API

Testing PaymentsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package TebexCheckout

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_TebexCheckout_PaymentsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PaymentsAPIService GetPaymentById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var txnId string

		resp, httpRes, err := apiClient.PaymentsAPI.GetPaymentById(context.Background(), txnId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PaymentsAPIService RefundPaymentById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var txnId string

		resp, httpRes, err := apiClient.PaymentsAPI.RefundPaymentById(context.Background(), txnId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
